#!/bin/sh
# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# CI guard: formally confirm the lxp syscall SURFACE against an offline reference.
# This is the coverage half of the syscall-conformance effort (the correctness half
# is the host golden suite, tests/suites/test_syscall_conformance.c).
#
# With no toolchain and no running code it cross-checks the source-of-truth sites:
#   include/lxp/lxp_syscall.h        — the LXP_NR_* number definitions
#   scripts/syscalls/arm-eabi.tbl    — the canonical ARM EABI numbers (the reference)
#   scripts/syscalls/dispositions.tsv— the frozen implemented/stub/refused/... partition
#   src/lxp_syscall.c / src/lxp_run.c— where each syscall is actually handled
# and regenerates docs/syscall-compat.md, failing if the committed copy drifted.
#
# POSIX sh + awk only (mawk-safe: no gawk 3-arg match / gensub).
#
# Usage:
#   scripts/syscalls/check-syscalls.sh                 # run all checks (CI)
#   scripts/syscalls/check-syscalls.sh --emit-matrix   # print the matrix to stdout
set -eu
cd "$(dirname "$0")/../.."

REF=scripts/syscalls/arm-eabi.tbl
TSV=scripts/syscalls/dispositions.tsv
HDR=include/lxp/lxp_syscall.h
DISP=src/lxp_syscall.c
RUN=src/lxp_run.c
MATRIX=docs/syscall-compat.md

for f in "$REF" "$TSV" "$HDR" "$DISP" "$RUN"; do
	[ -f "$f" ] || { echo "FAIL: missing $f"; exit 1; }
done

# Sets used by the coverage check + the matrix, extracted once.
CASES=$(mktemp); RUNLOOP=$(mktemp); ROWS=$(mktemp)
trap 'rm -f "$CASES" "$RUNLOOP" "$ROWS"' EXIT
grep -oE 'case LXP_NR_[A-Za-z0-9_]+' "$DISP" | sed 's/case LXP_NR_//' | sort -u > "$CASES"
grep -oE 'LXP_NR_[A-Za-z0-9_]+'      "$RUN"  | sed 's/LXP_NR_//'      | sort -u > "$RUNLOOP"

# Rows for the matrix: "<num>\t<name>\t<disposition>\t<note>", sorted by number.
awk -v tsv="$TSV" '
	BEGIN { while ((getline l < tsv) > 0) { if (l ~ /^#/ || l == "") continue;
		n = split(l, a, "\t"); if (n >= 2) { D[a[1]] = a[2]; NOTE[a[1]] = (n >= 3 ? a[3] : "") } } }
	$1 == "#define" && $2 ~ /^LXP_NR_/ { name = substr($2, 8);
		if ($3 ~ /^[0-9]+$/) printf "%s\t%s\t%s\t%s\n", $3, name, D[name], NOTE[name] }
' "$HDR" | sort -n > "$ROWS"

emit_matrix() {
	total=$(grep -c . "$ROWS")
	counts=$(awk -F'\t' '{ c[$3]++ } END {
		printf "%d implemented, %d benign-stub, %d refused-eopnotsupp, %d run-loop-handled, %d deliberately-enosys",
		       c["implemented"]+0, c["benign-stub"]+0, c["refused-eopnotsupp"]+0, c["run-loop-handled"]+0, c["deliberately-enosys"]+0 }' "$ROWS")
	cat <<EOF
# lxp syscall compatibility matrix

<!-- Generated by scripts/syscalls/check-syscalls.sh --emit-matrix. Do not edit by hand;
     CI fails if this file drifts from the sources. -->

Every syscall the lxp personality answers, cross-checked against the ARM EABI reference
(\`scripts/syscalls/arm-eabi.tbl\`) and classified in \`scripts/syscalls/dispositions.tsv\`.
Numbers come from \`include/lxp/lxp_syscall.h\`; dispositions are proved against the
handlers in \`src/lxp_syscall.c\` / \`src/lxp_run.c\` by the coverage guard.

Surface: $total LXP_NR_* — $counts.

| Number | Name | Disposition | Notes |
|---:|---|---|---|
EOF
	awk -F'\t' '{ printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4 }' "$ROWS"
}

# --emit-matrix: just print it (for `... --emit-matrix > docs/syscall-compat.md`).
if [ "${1:-}" = "--emit-matrix" ]; then
	emit_matrix
	exit 0
fi

fail=0

# ---- 1. Number cross-check ---------------------------------------------------
# Every LXP_NR_<name> must be a plain decimal equal to the canonical ARM EABI number.
report=$(awk -v ref="$REF" '
	BEGIN { while ((getline l < ref) > 0) { if (l ~ /^#/ || l == "") continue;
		if (split(l, a, "\t") >= 2) R[a[2]] = a[1] } }
	$1 == "#define" && $2 ~ /^LXP_NR_/ {
		name = substr($2, 8); val = $3; total++
		if (val !~ /^[0-9]+$/) { printf "NON-LITERAL   %-22s value=%s  (LXP_NR_ macro must be a plain decimal)\n", name, val; next }
		if (!(name in R))       { printf "NOT-IN-EABI   %-22s lxp=%s  (name absent from the ARM EABI reference)\n", name, val; next }
		if (R[name] + 0 != val + 0) { printf "MISMATCH      %-22s lxp=%s  canonical=%s\n", name, val, R[name] }
	}
	END { if (total < 100) printf "PARSE-ERROR   only %d LXP_NR_ lines parsed from the header\n", total }
' "$HDR")
if [ -n "$report" ]; then
	echo "FAIL: LXP_NR_* numbers disagree with the ARM EABI reference ($REF):"
	echo "$report" | sed 's/^/  /'; fail=1
else
	echo "OK: every LXP_NR_* number matches the ARM EABI reference."
fi

# ---- 2. Coverage / disposition cross-check -----------------------------------
# Every LXP_NR_* is classified, and each classification still matches the source:
# implemented/stub/refused have a dispatch case; run-loop-handled are intercepted in
# lxp_run.c and are NOT a case; deliberately-enosys have no case. Also flags stale rows.
report=$(awk -v tsv="$TSV" -v casesf="$CASES" -v runf="$RUNLOOP" '
	BEGIN {
		while ((getline l < tsv) > 0) { if (l ~ /^#/ || l == "") continue;
			if (split(l, a, "\t") >= 2) disp[a[1]] = a[2] }
		while ((getline l < casesf) > 0) if (l != "") C[l] = 1
		while ((getline l < runf)  > 0) if (l != "") RL[l] = 1
	}
	$1 == "#define" && $2 ~ /^LXP_NR_/ {
		name = substr($2, 8); H[name] = 1; total++
		if (!(name in disp)) { printf "UNCLASSIFIED    %-22s no row in dispositions.tsv\n", name; next }
		d = disp[name]
		if (d == "implemented" || d == "benign-stub" || d == "refused-eopnotsupp") {
			if (!(name in C)) printf "MISSING-CASE    %-22s classified %s but no `case LXP_NR_%s:` in lxp_syscall.c\n", name, d, name
		} else if (d == "run-loop-handled") {
			if (!(name in RL)) printf "MISSING-RUNLOOP %-22s classified run-loop-handled but absent from lxp_run.c\n", name
			if (name in C)     printf "UNEXPECTED-CASE %-22s run-loop-handled but ALSO a dispatch case\n", name
		} else if (d == "deliberately-enosys") {
			if (name in C)     printf "UNEXPECTED-CASE %-22s deliberately-enosys but has a dispatch case\n", name
		} else {
			printf "BAD-DISPOSITION %-22s unknown disposition \"%s\"\n", name, d
		}
	}
	END {
		for (k in disp) if (!(k in H)) printf "STALE-ROW       %-22s in dispositions.tsv but not a LXP_NR_ in the header\n", k
		if (total < 100) printf "PARSE-ERROR     only %d LXP_NR_ lines parsed\n", total
	}
' "$HDR")
if [ -n "$report" ]; then
	echo "FAIL: syscall dispositions disagree with the source:"
	echo "$report" | sed 's/^/  /'; fail=1
else
	echo "OK: all $(grep -c . "$ROWS") LXP_NR_* are classified and match the dispatcher / run loop."
fi

# ---- 3. Compatibility-matrix in-sync check -----------------------------------
tmp=$(mktemp)
emit_matrix > "$tmp"
if [ ! -f "$MATRIX" ] || ! diff -q "$MATRIX" "$tmp" >/dev/null 2>&1; then
	echo "FAIL: $MATRIX is out of sync — regenerate:"
	echo "  scripts/syscalls/check-syscalls.sh --emit-matrix > $MATRIX"
	[ -f "$MATRIX" ] && diff -u "$MATRIX" "$tmp" | head -30
	fail=1
else
	echo "OK: $MATRIX is in sync with the sources."
fi
rm -f "$tmp"

exit $fail
